### ISSUE TITLE
Checkboxes not checking/unchecking as expected

### ISSUE THREAD

**Issue by benkotch** [Aidurber/react-picky#128]
## Version
4.4.0
## Here's what went wrong:
Clicked on a field (div next to checkbox)

**Expected Behavior**
If already selected, checkbox changes to unselected
If not selected, checkbox changes to selected

**Actual Behavior**
Checkbox does not change state
Note: Submitted values are correct, this is just a UI issue.

The UI state stays the same while the selected value changes.
<img width="213" alt="Screen Shot 2019-04-26 at 10 06 34 AM" src="https://user-images.githubusercontent.com/380629/56824529-94aff800-680b-11e9-9915-bccd87083b47.png">
<img width="563" alt="Screen Shot 2019-04-26 at 10 06 02 AM" src="https://user-images.githubusercontent.com/380629/56824534-98437f00-680b-11e9-8516-4738dd143750.png">
<img width="562" alt="Screen Shot 2019-04-26 at 10 06 19 AM" src="https://user-images.githubusercontent.com/380629/56824535-98437f00-680b-11e9-90e6-767418699e1d.png">

Was not occurring in version 4.1.2. Unfortunately we are not sure when it stopped working correctly, but tested as not working in 4.4.0.

@Aidurber thanks for creating this picker, super useful!

**Comment by Aidurber** [comment]
@benkotch Thanks for reporting this and I'm sorry that I broke it. PR is building now with a fix. Should be working again shortly.

**Comment by benkotch** [comment]
@Aidurber thanks so much for the fast fix!

**Comment by Ihsan1122** [comment]
@benkotch  
sir, can you please guide me how are you making the already selected check boxes ?
Becasue i have updated the library but still cannot be able to change the UI state.
